name: Get Unity License File
on: workflow_dispatch
jobs:
  requestActivation:
    runs-on: ubuntu-latest
    steps:
      - name: Request manual activation file
        id: requestActivation
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.15f1  # Replace with your Unity version
      
      - name: Upload activation file
        uses: actions/upload-artifact@v4
        with:
          name: Unity_Activation_File
          path: ${{ steps.requestActivation.outputs.filePath }}
