name: Build Unity Project

on:
  push:
    tags:
      - 'v*' # Run workflow ONLY on version tags
  workflow_dispatch: # Allows manual triggering if needed

jobs:
  buildWindows:
    name: Build for Windows
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Cache LFS objects
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache the Unity Library folder to speed up builds
      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Windows-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Windows-

      # Run the Unity build
      - name: Build Windows Player
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows64
          buildName: ${{ github.repository_name }}
          buildMethod: '' # Leave empty to use the default build method
          versioning: Semantic
          allowDirtyBuild: true

      # Find and upload only the .exe file
      - name: Find and copy EXE file
        run: |
          mkdir -p exe-only
          find build/StandaloneWindows64 -name "*.exe" -exec cp {} exe-only/ \;
          
      # Upload only the .exe file
      - name: Upload Windows EXE
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.repository_name }}-Windows
          path: exe-only/*.exe
          retention-days: 14
          
  # Create GitHub Release with executables when a version tag is pushed
  createRelease:
    name: Create Release
    needs: [buildWindows, buildAndroid]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows Build
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.repository_name }}-Windows
          path: windows-build
      
      - name: Download Android Build
        uses: actions/download-artifact@v3
        with:
          name: ${{ github.repository_name }}-Android
          path: android-build
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-build/*.exe
            android-build/*.apk
            android-build/*.aab
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true

  buildAndroid:
    name: Build for Android
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Create LFS file list
        run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id

      - name: Cache LFS objects
        uses: actions/cache@v3
        id: lfs-cache
        with:
          path: .git/lfs
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}

      - name: Git LFS Pull
        run: |
          git lfs pull
          git add .
          git reset --hard

      # Cache the Unity Library folder to speed up builds
      - name: Cache Library folder
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-Android-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-Android-

      # Run the Unity build
      - name: Build Android Player
        uses: game-ci/unity-builder@v3
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          buildName: ${{ github.repository_name }}
          buildMethod: '' # Leave empty to use the default build method
          versioning: Semantic
          androidAppBundle: true
          androidKeystoreName: ${{ secrets.ANDROID_KEYSTORE_NAME }}
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          allowDirtyBuild: true

      # Find and upload only the .apk or .aab file
      - name: Find and copy APK/AAB file
        run: |
          mkdir -p apk-only
          find build/Android -name "*.apk" -o -name "*.aab" -exec cp {} apk-only/ \;
          
      # Upload only the .apk file
      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.repository_name }}-Android
          path: apk-only/*
          retention-days: 14
